# Generated by Django 3.0.3 on 2020-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(default='', max_length=100)),
                ('head1', models.CharField(default='', max_length=100)),
                ('head2', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
