# Generated by Django 3.0.3 on 2020-03-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200320_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phoneNo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
